version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.15.0
  aws-ecs: circleci/aws-ecs@1.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run Mocha tests
workflows:
  node-tests:
    jobs:
      - test
      # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
      - aws-ecr/build-and-push-image:
          repo: api-slowlyfood
          tag: "latest,${CIRCLE_SHA1}"
          dockerfile: Dockerfile
          path: .
          requires:
            - test
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "ECSApiSlowlyFood"
          cluster-name: "api-slowlyfood-cluster"
          service-name: "api-slowlyfood-service"
          container-image-name-updates: "container=api-slowlyfood-container,tag=${CIRCLE_SHA1}"
      # - aws-ecs/update-task-definition:
      #     requires:
      #       - aws-ecs/deploy-service-update
      #     container-env-var-updates: ""
      #     container-image-name-updates: "container=api-slowlyfood-container,tag=${CIRCLE_SHA1}"
      #     family: "ECSApiSlowlyFood"