version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run Mocha tests
workflows:
  node-tests:
    jobs:
      - test
      # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
      - aws-ecr/build-and-push-image:
          repo: api-slowlyfood
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: Dockerfile
          path: .
          requires:
            - test
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "ECSApiSlowlyFood"
          cluster-name: $CLUSTER_NAME
          service-name: "DefaulService"
          container-image-name-updates: "container=ECSApiSlowlyFood,tag=${CIRCLE_BRANCH}_${CIRCLE_SHA1}"
